eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

  server:
    enable-self-preservation: false

  instance:
      hostname: localhost

spring:
  application:
    name: eureka2

server:
  port: 8762