eureka:
  client:
    service-url:
      defaultZone: http://eureka2:8762/eureka/
    fetch-registry: true
    register-with-eureka: true

  server:
    enable-self-preservation: false

  instance:
    hostname: localhost

spring:
  application:
    name: eureka1

server:
  port: 8761